# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c140c7b814566f6e45d10279290d2d50d0c6879002652739b1161e5b958a4c195f496c5281d7841bd6c495dcbe01df01f08d8d6f647384b0c8f5a7a5b2ce4d0

test:
  secret_key_base: 760b697bca1c6417eaa91ce6133637327e0ccf0b5a07c51fa71dd36a12898294b69a61a67e4a9e13e9ee5cd772c98a7275cb9dfa01d962e017d06ca011366c38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
